- name: Create a tempdir
  file:
    state: directory
    path: "{{ temp_path }}"   

- name: Remove passphrase file, if it exists
  file:
    state: absent
    path: "{{ passphrase_file }}" 

- name: Create passphrase file
  file:
    state: touch
    path: "{{ passphrase_file }}" 

- name: Add passphrase to the file
  lineinfile:
    dest: "{{ passphrase_file }}"
    line: "{{ passphrase }}" 