---

# date string
date: "{{ lookup( 'pipe', 'date +%Y-%m-%d-%H-%M' ) }}"


# defaults file for ansible-docker-swarm
docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_' + docker_swarm_interface]['ipv4']['address'] }}"

# Validity period for node certificates (default 2160h0m0s)
docker_swarm_cert_expiry: '2160h0m0s'

# Dispatcher heartbeat period (default 5s)
docker_swarm_dispatcher_heartbeat_duration: '5s'

docker_swarm_interface: "eth0"
# docker_swarm_managers_ansible_group: 'docker-swarm-managers'

docker_swarm_config_networks: false
docker_swarm_config_settings: false

# Define Ansible group which contains all docker nodes
docker_swarm_nodes_ansible_group: 'docker-nodes'
docker_swarm_nodes_ansible_group_node_count: "{{ groups[docker_swarm_nodes_ansible_group] | count }}"

# Define Ansible group which contains your Docker swarm managers
docker_swarm_managers_ansible_group: 'docker-swarm-managers'
docker_swarm_managers_ansible_groups: '{{ groups[docker_swarm_managers_ansible_group] | sort }}'

docker_swarm_networks: []
  # - name: 'my_net'
  #   driver: 'overlay'
  #   state: 'present'
  # - name: 'test'
  #   driver: 'overlay'
  #   state: 'absent'
docker_swarm_port: "2377"


# Defines first node in docker_swarm_managers_ansible_group as primary
docker_swarm_primary_manager: '{{ docker_swarm_managers_ansible_groups[0] }}'

# Task history retention limit (default 5)
docker_swarm_task_history_limit: '5'

# Define Ansible group which contains you Docker swarm workers
docker_swarm_workers_ansible_group: 'docker-swarm-workers'


# TLS Certificates 

cert_template_file: /tmp/cert_template.txt

docker_cert_dir: /var/lib/docker/swarm/certificates 

docker_ca_key: "{{ docker_cert_dir }}/{{ inventory_hostname }}-ca-key.pem"

docker_ca_cert: "{{ docker_cert_dir }}/{{ inventory_hostname }}-ca.pem"

docker_csr_file: "{{ docker_cert_dir }}/{{ inventory_hostname }}-csr.pem"

docker_cert_file: "{{ docker_cert_dir }}/{{ inventory_hostname }}-cert.pem"

docker_key_file: "{{ docker_cert_dir }}/{{ inventory_hostname }}-key.pem"

dds_system_tmp: /tmp
dds_country: US
dds_state: North Carolina
dds_locality: Durham
dds_organization: Acme Corp
dds_host: 127.0.0.1
dds_common_name: "{{ dds_host }}" 
dds_passphrase: Phrase123!
dds_server_cert_path: /etc/docker
dds_client_cert_path: ~/.docker
dds_env_shell_path: "~"  
dds_install_shell: yes
dds_restart_docker: no 

# Signals
all_tasks_ok: "/etc/docker/.all_tasks_ok"