---
settings:
  ansible:
    env:
      ansible_keep_remote_files: 0
    paths:
      basedir: provisioners/ansible
      cfg: ansible.cfg
      playbooks:
        set: ".vagrant/.playbooks_grouped.yaml"
    mode: controller #standalone
    surrogate: ansible-controller
    vardir: ".vagrant/machines/%s/provisioners/ansible"
    default_include_statement: 'import_playbook'
    windows_helper_script: scripts/windows.ansible-playbook.sh
    scratch:
      playbook_name: playbook.scratch.yaml
    options:
      global:
        config_file: "<%= (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil ? :'/vagrant' : :'.' %>/ansible.cfg"
        # extra_vars:
          # clear_module_cache: true
          # ansible_ssh_user: 'vagrant'
        # raw_ssh_args:
        #   - '-o UserKnownHostsFile=/dev/null'
        #   - '-o StrictHostKeyChecking=no'
        #   - '-o PasswordAuthentication=no'
        #   - '-o IdentitiesOnly=yes'
        become: true
      local:
        install_mode: pip
  environment:
    defaults: 
      context: etejeda
    context_file: .vagrant/.environment_context
    context: <%= File.read('.vagrant/.environment_context') if File.exist?('.vagrant/.environment_context') rescue '' %>
    node:
      definitions:
        exclude_paths: 
          - playbooks
          - roles
          - group_vars
          - host_vars
          - templates
          - files
        include_files: .*.\.yaml
        exclude_files:
          - inventory.yaml
          - inventory.yml
      provisioners:
          env_hash:
            - node_definition_path
            - name
    basedir: environments
    nodesdir: machines
    skeleton:
      - group_vars/all
      - host_vars
      - machines
      - templates
    sizing:
      small:
        memory: 512
        cpus: 1
      medium:
        memory: 1024
        cpus: 1
      large:    
        memory: 2048
        cpus: 2
      xlarge:    
        memory: 4096
        cpus: 4
  logging:
    debug: false
    logs_dir: ".vagrant/var/log"
  semaphores:
    debug: ".vagrant/.debug"
  managed_nodes:
    posix:
      required_key: ssh
      required_properties:
        - port
    windows:
      required_key: winrm
      required_properties:
        - port
  # misc
  misc:
    patterns:
      node:
        up: ".*(running|reachable)"
  # Platform detection
  platform:
    is_windows: <%= (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil %>
    is_osx: <%= (/darwin/ =~ RUBY_PLATFORM) != nil %>
    is_linux: <%= (/linux/ =~ RUBY_PLATFORM) != nil %>
  project:
    editor: 
      path: "C:\\progra~1\\SUBLIM~1\\subl.exe"
      options: "-a"
    ssh:
      path: "C:\\Users\\etejeda\\Desktop\\tools\\c\\cmder\\vendor\\git-for-windows\\usr\\bin\\ssh.exe"
    is_vagrant: "<%= defined?(%{Vagrant}) ? :'true' : :'false' %>"
    project_path: "<%= File.expand_path('.', Dir.pwd) %>"
    requirements:
      plugins:
        mandatory:
          - vagrant-hosts # Manages static DNS on vagrant guests
        libvirt:
          - vagrant-hostsupdater # Adds an entry to your /etc/hosts file on the host system
          - vagrant-google # Google Cloud Platform Provider - for managing GCP Compute Instances
          - vagrant-libvirt
        virtualbox:
          - vagrant-disksize
          - vagrant-google
          - vagrant-hostsupdater
          - vagrant-vbguest
  puppet:
    basedir: provisioners/puppet
  starttime: <%= Time.now %>
  testing:
    ternary: "<%= defined?(%{somevar}) ? :'ternary - true' : :'ternary - false' %>"
  user:
    homedir: "<%= File.expand_path('~') %>"
    name: "<%= ENV['USER'] || ENV['USERNAME'] %>"
  vagrant:
    api_version: 2
    require_version: ">= 1.7.2"
    commands:
      noexec: <%= Dir.glob("lib/commands/*.rb").map { |file| File.basename(file, ".rb") } %>
      adhoc: 
        files: lib/commands/*.rb
    defaults:
      autostart: true
      config:
        boot_timeout: 300
      nodes:
        keys:
          box: 'ubuntu/xenial64'
          desktop: false
          provision: true
          natdnshostresolver1: "'on'"
          VBoxInternal2:
            SharedFoldersEnableSymlinksCreate:
              v_root: 1
        size: medium
    default_provider: 'virtualbox'
    templates:
      node: etc/templates/node.yaml
    provider_order: 
      - 'libvirt'
      - 'virtualbox'
    is_true: true
    box_download_insecure: true
    ssh:
      private_key_path:
        - 'etc/sshkeys/insecure'
        # - 'etc/sshkeys/secure'
      insert_key: false
      username: vagrant
    synced_folder:
      defaults:
        type: virtualbox
        create: false
        owner: vagrant
        group: vagrant
        disabled: false
        mount_options: []
        nfs:
          udp: true
          # version: 3
          # options:
          #   - rw
          #   - no_subtree_check
          #   - all_squash
          #   - async
        rsync:
          args: 
            - '--verbose'
            - '--archive'
            - '--delete'
            - '-z'
          auto: true
          exclude: 
            - '.vagrant/'
        smb:
          mount_options: []
    no_mount_vagrant: false
    # disable nfs for windows vhosts (for now)
    # see https://github.com/winnfsd/vagrant-winnfsd/issues/53
    use_nfs: false
    nfs_mount_options: 
      - rw
      - nolock
      - vers=3
      - udp
      - noatime
      - actimeo=1
    vm_network_default_mode: 'private_network'
    vm_usable_port_range_start: 2200
    vm_usable_port_range_end: 10000
    local_data_dir: ".vagrant"
    basedir:
      posix: '<%= Dir.pwd %>'
      windows: '/vagrant'
    vcpu_minimum: 1
    vmem_minimum: 512
    vcpu_allocation_ratio: 1
    vmem_allocation_ratio: 1
