---
settings:
  ansible:
    surrogate: ansible.treno.local
    options:
      global:
        config_file: <%= (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil ? :'/vagrant' : :'.' %>/ansible.cfg    